// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Net5.Rest.Infrastructure.Data.Entities
{
    [Table("OnlineCourse")]
    public partial class OnlineCourse
    {
        [Key]
        [Column("CourseID")]
        public int CourseId { get; set; }
        [Required]
        [Column("URL")]
        [StringLength(100)]
        public string Url { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty("OnlineCourse")]
        public virtual Course Course { get; set; }
    }
}