// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Net5.Rest.Infrastructure.Data.Entities
{
    [Table("StudentGrade")]
    public partial class StudentGrade
    {
        [Key]
        [Column("EnrollmentID")]
        public int EnrollmentId { get; set; }
        [Column("CourseID")]
        public int CourseId { get; set; }
        [Column("StudentID")]
        public int StudentId { get; set; }
        [Column(TypeName = "decimal(3, 2)")]
        public decimal? Grade { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty("StudentGrades")]
        public virtual Course Course { get; set; }
        [ForeignKey(nameof(StudentId))]
        [InverseProperty(nameof(Person.StudentGrades))]
        public virtual Person Student { get; set; }
    }
}